# Lion API

Lion is a basic localization service using `git` as the backend for storing translations.

## Request headers

All requests to Lion must include the following headers:

- `Lion-Api-Key`
- `Lion-Api-Secret`
- `Lion-Api-Version`

# Group Projects

## Project collection [/projects]

### List projects [GET]

List all configured projects

+ Request (application/json)

    + Header

              Lion-Api-Version: v1

+ Response 200 (application/json)

    + Header

              Lion-Api-Version: v1

    + Body

              {
                "projects": [
                    "projectA": {
                        "name" "projectA" // All project details
                    }
                ]
              }

## Project management [/project/{name}]

+ Parameters

    + name (required, string) ... Project name

### Get project [GET]

Fetch project details, given the projects' name.

+ Request (application/json)

    + Header

              Lion-Api-Key: <YOUR_API_KEY>
              Lion-Api-Secret: <YOUR_API_SECRET>
              Lion-Api-Version: v1

+ Response 200 (application/json)

    + Header

              Lion-Api-Version: v1

    + Body

              {
                "name": "Project name",
                "resources": [
                  "resource1",
                  "..."
                ]
              }

+ Response 401 (application/json)

    + Header

              Lion-Api-Version: v1

+ Response 403 (application/json)

    + Header

              Lion-Api-Version: v1

+ Response 404 (application/json)

    + Header

              Lion-Api-Version: v1
