# Lion API

Lion is a basic localization service using `git` as the backend for storing translations.

## Request headers

All requests to Lion must include the following headers:

- `Lion-API-key`
- `Lion-API-secret`
- `Lion-API-version`

# Projects

## Project management [/project/{name}]

+ Parameters

	+ name (required, string) ... Project name

### Get project [GET]

Fetch project details, given the projects' name.

+ Request (application/json)

	+ Header

		Lion-API-key: <YOUR_API_KEY>
		Lion-API-secret: <YOUR_API_SECRET>
		Lion-API-version: v1

+ Response 200 (application/json)

	+ Header

		Lion-API-version: v1

	+ Body

		{
			"name": "Project name",
			"resources": [
				"resource1",
				"..."
			]
		}

+ Response 401 (application/json)

	+ Header

		Lion-API-version: v1

+ Response 403 (application/json)

	+ Header

		Lion-API-version: v1

+ Response 404 (application/json)

	+ Header

		Lion-API-version: v1
